/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agentieturism;

import static agentieturism.ConexiuneBD.codFinally;
import static agentieturism.ConexiuneBD.getConnection;
import static agentieturism.PrimaPagina.campUser;

import com.itextpdf.text.pdf.DefaultFontMapper;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;


/**
 * @author Diana
 */
public class PaginaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PaginaAdmin
     */
    public PaginaAdmin() {
        initComponents();
        setPanelVisible(pagPrincAdmin);
        afiseazaAngajati();
        afiseazaAgentii1();
        afiseazaFurnizori();
        fillFurnizori();
        fillFunctie();
        fillAgentie();
        fillAgentie1();
        setDateCont();
        fillComboAn();
        fillComboAn1();
        fillComboAn2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean anBisect(int an) {
        return ((an % 4 == 0) && (an % 100 != 0)) || an % 400 == 0;
    }

    private void afiseazaAngajati() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabelAngajati.getModel();
            Connection conn = getConnection();
            String sql = "SELECT * FROM angajat";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa angajatii!");
        }
    }

    private void afiseazaAgentii1() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabelAgentii.getModel();
            Connection conn = getConnection();
            String sql = "SELECT * FROM agentie";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa agentiile!");
        }
    }

    private void afiseazaFurnizori() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabelFurnizori.getModel();
            Connection conn = getConnection();
            String sql = "SELECT * FROM furnizori";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getInt(1), rs.getString(2)});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa furnizorii!");
        }
    }

    private void fillFurnizori() {
        try {
            Connection conn = getConnection();
            String sql = "SELECT * FROM furnizori";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String test = rs.getString("Firma");
                furnizori.addItem(test);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa furnizorii!");
        }
    }

    private void fillFunctie() {
        try {
            Connection conn = getConnection();
            String sql = "SELECT * FROM functie";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String test = rs.getString("Den_functie");
                functieAng.addItem(test);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa functiile anagajatilor!");
        }
    }

    private void fillAgentie() {
        try {
            Connection conn = getConnection();
            String sql = "SELECT * FROM agentie";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String test = rs.getString("denumire");
                agentieAng.addItem(test);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa agentiile!");
        }
    }

    private void fillAgentie1() {
        try {
            Connection conn = getConnection();
            String sql = "SELECT * FROM agentie";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                String test = rs.getString("denumire");
                agentieC.addItem(test);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot accesa agentiile!");
        }
    }


    private void setPanelVisible(JPanel panel) {
        ArrayList<JPanel> jpaneluri = new ArrayList<>();
        jpaneluri.add(pagPrincAdmin);
        jpaneluri.add(vizualizareFurnizori);
        jpaneluri.add(vizualizareAngajati);
        jpaneluri.add(adaugareContract);
        jpaneluri.add(adaugareAngajat);
        jpaneluri.add(cautareAngajat);
        jpaneluri.add(contulMeu);
        jpaneluri.add(angajatiVizSiAdaug);
        jpaneluri.add(raportPanel);
        pagPrincAdmin.setVisible(false);
        vizualizareFurnizori.setVisible(false);
        adaugareContract.setVisible(false);
        vizualizareAngajati.setVisible(false);
        adaugareAngajat.setVisible(false);
        cautareAngajat.setVisible(false);
        contulMeu.setVisible(false);
        angajatiVizSiAdaug.setVisible(false);
        raportPanel.setVisible(false);
        for (JPanel i : jpaneluri) {
            if (i == panel) {
                panel.setVisible(true);
            }
        }
    }

    private void setDateCont() {
        try {
            Connection conn = getConnection();
            String getDateAdmin = "SELECT * FROM angajat WHERE cont=?";
            PreparedStatement ps = conn.prepareStatement(getDateAdmin);
            ps.setString(1, campUser.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                numeCont.setText(rs.getString("Nume"));
                prenumeCont.setText(rs.getString("Prenume"));
                telefonCont.setText(rs.getString("Telefon"));
                emailCont.setText(rs.getString("Email"));
                contCont.setText(rs.getString("Cont"));
                parolaCont.setText(rs.getString("Parola"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate accesa contul!");
        }
    }

    private void fillComboAn() {
        for (int i = 2019; i >= 1990; i--)
            anul.addItem(Integer.toString(i));
        for (int i = 1; i <= 12; i++)
            luna.addItem(Integer.toString(i));

    }

    private void fillComboAn1() {
        for (int i = 2019; i >= 1990; i--)
            comboAnul.addItem(Integer.toString(i));
        for (int i = 1; i <= 12; i++)
            comboLuna.addItem(Integer.toString(i));

    }

    private void fillComboAn2() {
        for (int i = 2019; i >= 1990; i--)
            comboAnul1.addItem(Integer.toString(i));
        for (int i = 1; i <= 12; i++)
            comboLuna1.addItem(Integer.toString(i));

    }

    public static void writeChartToPDF(JFreeChart chart, int width, int height, String fileName) {

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        vizualizareAngajati = new javax.swing.JPanel();
        titluAngajati = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAngajati = new javax.swing.JTable();
        butonInapoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adaugareContract = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelNumeAngajat = new javax.swing.JLabel();
        labelFurnizor = new javax.swing.JLabel();
        numeAngajat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        furnizori = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        contractA4 = new javax.swing.JTextArea();
        anul = new javax.swing.JComboBox<>();
        luna = new javax.swing.JComboBox<>();
        ziua = new javax.swing.JComboBox<>();
        salvareContract = new javax.swing.JButton();
        butonInapoiContract = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        agentieC = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pagPrincAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        furnizoriButon = new javax.swing.JButton();
        contracteButon = new javax.swing.JButton();
        contulMeuButon = new javax.swing.JButton();
        agentiiButon = new javax.swing.JButton();
        deconectareButon = new javax.swing.JButton();
        logoAdmin = new javax.swing.JLabel();
        rapoarteButon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        angajatiVizSiAdaug = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelAgentii = new javax.swing.JTable();
        titluAng = new javax.swing.JLabel();
        tlfAg1 = new javax.swing.JTextField();
        denAg1 = new javax.swing.JTextField();
        labelDen1 = new javax.swing.JLabel();
        labelTelefon1 = new javax.swing.JLabel();
        addAg1 = new javax.swing.JTextField();
        labelAdresa1 = new javax.swing.JLabel();
        butonInapoiAng = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        raportPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboAnul = new javax.swing.JComboBox<>();
        comboLuna = new javax.swing.JComboBox<>();
        comboZiua = new javax.swing.JComboBox<>();
        comboAnul1 = new javax.swing.JComboBox<>();
        comboLuna1 = new javax.swing.JComboBox<>();
        comboZiua1 = new javax.swing.JComboBox<>();
        butonAfisare = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelRaport = new javax.swing.JTable();
        butonBDF = new javax.swing.JButton();
        butonDiagrama = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        contulMeu = new javax.swing.JPanel();
        titluContulMeu = new javax.swing.JLabel();
        imgProfilAng = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        parolaCont = new javax.swing.JTextField();
        numeCont = new javax.swing.JTextField();
        prenumeCont = new javax.swing.JTextField();
        emailCont = new javax.swing.JTextField();
        telefonCont = new javax.swing.JTextField();
        contCont = new javax.swing.JTextField();
        butonInapoiCont = new javax.swing.JButton();
        butonSalveaza = new javax.swing.JButton();
        adaugareAngajat = new javax.swing.JPanel();
        labelNume = new javax.swing.JLabel();
        labelPrenume = new javax.swing.JLabel();
        labelTelefon = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelCont = new javax.swing.JLabel();
        labelParola = new javax.swing.JLabel();
        labelFunctie = new javax.swing.JLabel();
        numeAng = new javax.swing.JTextField();
        prenAng = new javax.swing.JTextField();
        tlfAng = new javax.swing.JTextField();
        mailAng = new javax.swing.JTextField();
        contAng = new javax.swing.JTextField();
        parolaAng = new javax.swing.JTextField();
        functieAng = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        labelAgentie = new javax.swing.JLabel();
        butonInapoiAdaugare = new javax.swing.JButton();
        agentieAng = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        vizualizareFurnizori = new javax.swing.JPanel();
        titluFurnizori = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelFurnizori = new javax.swing.JTable();
        inapoiPagAdmin = new javax.swing.JButton();
        butonAdaugaContract = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cautareAngajat = new javax.swing.JPanel();
        titluCautareAng = new javax.swing.JLabel();
        radioNume = new javax.swing.JRadioButton();
        radioCod = new javax.swing.JRadioButton();
        fieldCautare = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelAngajat = new javax.swing.JTable();
        butonCautare = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        meniuAdmin = new javax.swing.JMenuBar();
        vizualizareMeniu = new javax.swing.JMenu();
        vizAngMeniuItem = new javax.swing.JMenuItem();
        vizFurnizorMeniuItem = new javax.swing.JMenuItem();
        adaugareMeniu = new javax.swing.JMenu();
        adaugareAngMeniuItem = new javax.swing.JMenuItem();
        adaugareContractItem = new javax.swing.JMenuItem();
        cautareMeniu = new javax.swing.JMenu();
        cautareAngItem = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        vizualizareAngajati.setLayout(null);

        titluAngajati.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        titluAngajati.setText("ANGAJATI");
        vizualizareAngajati.add(titluAngajati);
        titluAngajati.setBounds(40, 10, 110, 22);

        tabelAngajati.setBackground(new java.awt.Color(204, 204, 204));
        tabelAngajati.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelAngajati.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Cod ", "Nume", "Prenume", "Telefon", "Adresa"
                }
        ));
        jScrollPane1.setViewportView(tabelAngajati);
        if (tabelAngajati.getColumnModel().getColumnCount() > 0) {
            tabelAngajati.getColumnModel().getColumn(0).setMinWidth(40);
            tabelAngajati.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelAngajati.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        vizualizareAngajati.add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 690, 260);

        butonInapoi.setBackground(new java.awt.Color(0, 102, 102));
        butonInapoi.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonInapoi.setForeground(new java.awt.Color(255, 255, 255));
        butonInapoi.setText("Inapoi");
        butonInapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonInapoiActionPerformed(evt);
            }
        });
        vizualizareAngajati.add(butonInapoi);
        butonInapoi.setBounds(270, 380, 90, 40);
        vizualizareAngajati.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 200);

        getContentPane().add(vizualizareAngajati);
        vizualizareAngajati.setBounds(0, 0, 700, 480);

        adaugareContract.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel4.setText("CONTRACT NOU");
        adaugareContract.add(jLabel4);
        jLabel4.setBounds(89, 38, 138, 20);

        labelData.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        labelData.setText("Data");
        adaugareContract.add(labelData);
        labelData.setBounds(20, 230, 40, 20);

        labelNumeAngajat.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        labelNumeAngajat.setText("Nume angajat");
        adaugareContract.add(labelNumeAngajat);
        labelNumeAngajat.setBounds(30, 90, 83, 15);

        labelFurnizor.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        labelFurnizor.setText("Furnizor");
        adaugareContract.add(labelFurnizor);
        labelFurnizor.setBounds(30, 170, 51, 15);

        numeAngajat.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        numeAngajat.setText("Popescu Adrian");
        adaugareContract.add(numeAngajat);
        numeAngajat.setBounds(160, 90, 120, 21);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adauga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        adaugareContract.add(jButton1);
        jButton1.setBounds(190, 290, 92, 42);

        furnizori.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        adaugareContract.add(furnizori);
        furnizori.setBounds(160, 170, 120, 21);

        contractA4.setColumns(20);
        contractA4.setRows(5);
        jScrollPane3.setViewportView(contractA4);

        adaugareContract.add(jScrollPane3);
        jScrollPane3.setBounds(320, 20, 340, 400);

        anul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulActionPerformed(evt);
            }
        });
        adaugareContract.add(anul);
        anul.setBounds(60, 230, 90, 20);

        luna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunaActionPerformed(evt);
            }
        });
        adaugareContract.add(luna);
        luna.setBounds(170, 230, 70, 20);

        adaugareContract.add(ziua);
        ziua.setBounds(250, 230, 60, 20);

        salvareContract.setBackground(new java.awt.Color(0, 102, 102));
        salvareContract.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        salvareContract.setForeground(new java.awt.Color(255, 255, 255));
        salvareContract.setText("Salveaza");
        salvareContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvareContractActionPerformed(evt);
            }
        });
        adaugareContract.add(salvareContract);
        salvareContract.setBounds(40, 290, 100, 40);

        butonInapoiContract.setBackground(new java.awt.Color(0, 102, 102));
        butonInapoiContract.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        butonInapoiContract.setForeground(new java.awt.Color(255, 255, 255));
        butonInapoiContract.setText("Inapoi");
        butonInapoiContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonInapoiContractActionPerformed(evt);
            }
        });
        adaugareContract.add(butonInapoiContract);
        butonInapoiContract.setBounds(110, 390, 100, 23);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        jLabel5.setText("Agentie");
        adaugareContract.add(jLabel5);
        jLabel5.setBounds(30, 130, 70, 20);

        adaugareContract.add(agentieC);
        agentieC.setBounds(160, 130, 120, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/bgFurnizoriAdmin.jpg"))); // NOI18N
        adaugareContract.add(jLabel6);
        jLabel6.setBounds(0, 0, 700, 480);

        getContentPane().add(adaugareContract);
        adaugareContract.setBounds(0, 0, 700, 480);

        pagPrincAdmin.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel1.setText("PAGINA ADMINISTRATOR");
        pagPrincAdmin.add(jLabel1);
        jLabel1.setBounds(243, 24, 218, 20);

        furnizoriButon.setBackground(new java.awt.Color(0, 102, 102));
        furnizoriButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        furnizoriButon.setForeground(new java.awt.Color(255, 255, 255));
        furnizoriButon.setText("FURNIZORI");
        furnizoriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furnizoriButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(furnizoriButon);
        furnizoriButon.setBounds(250, 170, 130, 40);

        contracteButon.setBackground(new java.awt.Color(0, 102, 102));
        contracteButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contracteButon.setForeground(new java.awt.Color(255, 255, 255));
        contracteButon.setText("CONTRACTE");
        contracteButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contracteButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(contracteButon);
        contracteButon.setBounds(50, 260, 130, 40);

        contulMeuButon.setBackground(new java.awt.Color(0, 102, 102));
        contulMeuButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contulMeuButon.setForeground(new java.awt.Color(255, 255, 255));
        contulMeuButon.setText("CONTUL MEU");
        contulMeuButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contulMeuButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(contulMeuButon);
        contulMeuButon.setBounds(250, 260, 140, 40);

        agentiiButon.setBackground(new java.awt.Color(0, 102, 102));
        agentiiButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        agentiiButon.setForeground(new java.awt.Color(255, 255, 255));
        agentiiButon.setText("AGENTII");
        agentiiButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentiiButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(agentiiButon);
        agentiiButon.setBounds(60, 170, 110, 40);

        deconectareButon.setBackground(new java.awt.Color(0, 102, 102));
        deconectareButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deconectareButon.setForeground(new java.awt.Color(255, 255, 255));
        deconectareButon.setText("IESIRE");
        deconectareButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconectareButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(deconectareButon);
        deconectareButon.setBounds(270, 340, 100, 40);

        logoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/logo.jpg"))); // NOI18N
        pagPrincAdmin.add(logoAdmin);
        logoAdmin.setBounds(10, 10, 110, 115);

        rapoarteButon.setBackground(new java.awt.Color(0, 102, 102));
        rapoarteButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rapoarteButon.setForeground(new java.awt.Color(255, 255, 255));
        rapoarteButon.setText("RAPOARTE");
        rapoarteButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapoarteButonActionPerformed(evt);
            }
        });
        pagPrincAdmin.add(rapoarteButon);
        rapoarteButon.setBounds(50, 340, 130, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/bgAdmin.jpg"))); // NOI18N
        pagPrincAdmin.add(jLabel9);
        jLabel9.setBounds(0, 0, 700, 480);

        getContentPane().add(pagPrincAdmin);
        pagPrincAdmin.setBounds(0, 0, 700, 480);

        angajatiVizSiAdaug.setPreferredSize(new java.awt.Dimension(700, 480));
        angajatiVizSiAdaug.setLayout(null);

        tabelAgentii.setBackground(new java.awt.Color(204, 204, 204));
        tabelAgentii.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelAgentii.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Cod ", "Denumire", "Adresa", "Telefon"
                }
        ));
        tabelAgentii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAgentiiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelAgentii);
        if (tabelAgentii.getColumnModel().getColumnCount() > 0) {
            tabelAgentii.getColumnModel().getColumn(0).setMinWidth(40);
            tabelAgentii.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelAgentii.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        angajatiVizSiAdaug.add(jScrollPane5);
        jScrollPane5.setBounds(0, 60, 690, 120);

        titluAng.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        titluAng.setText("AGENTII");
        angajatiVizSiAdaug.add(titluAng);
        titluAng.setBounds(280, 20, 100, 20);

        tlfAg1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        angajatiVizSiAdaug.add(tlfAg1);
        tlfAg1.setBounds(300, 310, 160, 30);

        denAg1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        denAg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denAg1ActionPerformed(evt);
            }
        });
        angajatiVizSiAdaug.add(denAg1);
        denAg1.setBounds(300, 210, 160, 30);

        labelDen1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelDen1.setText("Denumire");
        angajatiVizSiAdaug.add(labelDen1);
        labelDen1.setBounds(200, 220, 80, 17);

        labelTelefon1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelTelefon1.setText("Telefon");
        angajatiVizSiAdaug.add(labelTelefon1);
        labelTelefon1.setBounds(200, 320, 70, 17);

        addAg1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        angajatiVizSiAdaug.add(addAg1);
        addAg1.setBounds(300, 260, 160, 30);

        labelAdresa1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelAdresa1.setText("Adresa");
        angajatiVizSiAdaug.add(labelAdresa1);
        labelAdresa1.setBounds(200, 270, 60, 17);

        butonInapoiAng.setBackground(new java.awt.Color(0, 102, 102));
        butonInapoiAng.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonInapoiAng.setForeground(new java.awt.Color(255, 255, 255));
        butonInapoiAng.setText("Inapoi");
        butonInapoiAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonInapoiAngActionPerformed(evt);
            }
        });
        angajatiVizSiAdaug.add(butonInapoiAng);
        butonInapoiAng.setBounds(460, 390, 120, 40);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Adauga");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        angajatiVizSiAdaug.add(jButton4);
        jButton4.setBounds(140, 390, 130, 40);

        getContentPane().add(angajatiVizSiAdaug);
        angajatiVizSiAdaug.setBounds(0, 0, 700, 480);

        raportPanel.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel10.setText("RAPORT PRIVIND DESTINATIILE CELE MAI CAUTATE");
        raportPanel.add(jLabel10);
        jLabel10.setBounds(120, 10, 450, 20);

        jLabel18.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel18.setText("Selectati perioada");
        raportPanel.add(jLabel18);
        jLabel18.setBounds(290, 40, 130, 30);

        comboAnul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboAnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAnulActionPerformed(evt);
            }
        });
        raportPanel.add(comboAnul);
        comboAnul.setBounds(170, 90, 120, 23);

        comboLuna.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboLuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLunaActionPerformed(evt);
            }
        });
        raportPanel.add(comboLuna);
        comboLuna.setBounds(310, 90, 100, 23);

        comboZiua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        raportPanel.add(comboZiua);
        comboZiua.setBounds(430, 90, 60, 23);

        comboAnul1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboAnul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAnul1ActionPerformed(evt);
            }
        });
        raportPanel.add(comboAnul1);
        comboAnul1.setBounds(170, 140, 120, 23);

        comboLuna1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboLuna1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLuna1ActionPerformed(evt);
            }
        });
        raportPanel.add(comboLuna1);
        comboLuna1.setBounds(310, 140, 100, 23);

        comboZiua1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        raportPanel.add(comboZiua1);
        comboZiua1.setBounds(430, 140, 60, 23);

        butonAfisare.setBackground(new java.awt.Color(0, 102, 102));
        butonAfisare.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonAfisare.setForeground(new java.awt.Color(255, 255, 255));
        butonAfisare.setText("Afiseaza");
        butonAfisare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAfisareActionPerformed(evt);
            }
        });
        raportPanel.add(butonAfisare);
        butonAfisare.setBounds(300, 190, 110, 40);

        tabelRaport.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Destinatie", "Data plecare", "Data sosire", "Numar rezervari"
                }
        ));
        jScrollPane6.setViewportView(tabelRaport);

        raportPanel.add(jScrollPane6);
        jScrollPane6.setBounds(100, 240, 510, 110);

        butonBDF.setBackground(new java.awt.Color(0, 102, 102));
        butonBDF.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonBDF.setForeground(new java.awt.Color(255, 255, 255));
        butonBDF.setText("Genereaza PDF");
        butonBDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonBDFActionPerformed(evt);
            }
        });
        raportPanel.add(butonBDF);
        butonBDF.setBounds(130, 360, 150, 40);

        butonDiagrama.setBackground(new java.awt.Color(0, 102, 102));
        butonDiagrama.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonDiagrama.setForeground(new java.awt.Color(255, 255, 255));
        butonDiagrama.setText("Diagrama");
        butonDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonDiagramaActionPerformed(evt);
            }
        });
        raportPanel.add(butonDiagrama);
        butonDiagrama.setBounds(320, 360, 110, 40);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Inapoi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        raportPanel.add(jButton3);
        jButton3.setBounds(490, 362, 90, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/clientbg.jpg"))); // NOI18N
        raportPanel.add(jLabel19);
        jLabel19.setBounds(0, 0, 690, 500);

        getContentPane().add(raportPanel);
        raportPanel.setBounds(0, 0, 700, 530);

        contulMeu.setMinimumSize(new java.awt.Dimension(700, 480));
        contulMeu.setLayout(null);

        titluContulMeu.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        titluContulMeu.setText("CONTUL MEU");
        contulMeu.add(titluContulMeu);
        titluContulMeu.setBounds(290, 70, 120, 20);

        imgProfilAng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/imgProfil.png"))); // NOI18N
        contulMeu.add(imgProfilAng);
        imgProfilAng.setBounds(30, 20, 116, 120);

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel11.setText("Nume");
        contulMeu.add(jLabel11);
        jLabel11.setBounds(50, 190, 60, 17);

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel12.setText("Prenume");
        contulMeu.add(jLabel12);
        jLabel12.setBounds(40, 240, 80, 17);

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel14.setText("Telefon");
        contulMeu.add(jLabel14);
        jLabel14.setBounds(50, 300, 60, 17);

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setText("Email");
        contulMeu.add(jLabel15);
        jLabel15.setBounds(360, 190, 70, 17);

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel16.setText("Cont");
        contulMeu.add(jLabel16);
        jLabel16.setBounds(360, 240, 50, 17);

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel17.setText("Parola");
        contulMeu.add(jLabel17);
        jLabel17.setBounds(360, 290, 60, 20);

        parolaCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parolaContActionPerformed(evt);
            }
        });
        contulMeu.add(parolaCont);
        parolaCont.setBounds(440, 290, 140, 20);

        numeCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeContActionPerformed(evt);
            }
        });
        contulMeu.add(numeCont);
        numeCont.setBounds(130, 190, 140, 20);

        prenumeCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenumeContActionPerformed(evt);
            }
        });
        contulMeu.add(prenumeCont);
        prenumeCont.setBounds(130, 240, 140, 20);

        emailCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailContActionPerformed(evt);
            }
        });
        contulMeu.add(emailCont);
        emailCont.setBounds(440, 190, 170, 20);

        telefonCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonContActionPerformed(evt);
            }
        });
        contulMeu.add(telefonCont);
        telefonCont.setBounds(130, 290, 140, 20);

        contCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contContActionPerformed(evt);
            }
        });
        contulMeu.add(contCont);
        contCont.setBounds(440, 240, 140, 20);

        butonInapoiCont.setBackground(new java.awt.Color(0, 102, 102));
        butonInapoiCont.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonInapoiCont.setForeground(new java.awt.Color(255, 255, 255));
        butonInapoiCont.setText("Inapoi");
        butonInapoiCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonInapoiContActionPerformed(evt);
            }
        });
        contulMeu.add(butonInapoiCont);
        butonInapoiCont.setBounds(440, 360, 120, 40);

        butonSalveaza.setBackground(new java.awt.Color(0, 102, 102));
        butonSalveaza.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonSalveaza.setForeground(new java.awt.Color(255, 255, 255));
        butonSalveaza.setText("Salveaza");
        butonSalveaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSalveazaActionPerformed(evt);
            }
        });
        contulMeu.add(butonSalveaza);
        butonSalveaza.setBounds(130, 360, 120, 40);

        getContentPane().add(contulMeu);
        contulMeu.setBounds(0, 0, 700, 480);

        adaugareAngajat.setLayout(null);

        labelNume.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelNume.setText("Nume");
        adaugareAngajat.add(labelNume);
        labelNume.setBounds(60, 110, 42, 17);

        labelPrenume.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelPrenume.setText("Prenume");
        adaugareAngajat.add(labelPrenume);
        labelPrenume.setBounds(400, 110, 63, 17);

        labelTelefon.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelTelefon.setText("Telefon");
        adaugareAngajat.add(labelTelefon);
        labelTelefon.setBounds(50, 160, 55, 17);

        labelEmail.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelEmail.setText("Email");
        adaugareAngajat.add(labelEmail);
        labelEmail.setBounds(410, 160, 40, 17);

        labelCont.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelCont.setText("Cont");
        adaugareAngajat.add(labelCont);
        labelCont.setBounds(70, 210, 33, 17);

        labelParola.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelParola.setText("Parola");
        adaugareAngajat.add(labelParola);
        labelParola.setBounds(410, 210, 45, 17);

        labelFunctie.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelFunctie.setText("Functie");
        adaugareAngajat.add(labelFunctie);
        labelFunctie.setBounds(60, 270, 52, 17);

        numeAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(numeAng);
        numeAng.setBounds(140, 103, 160, 30);

        prenAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(prenAng);
        prenAng.setBounds(480, 103, 160, 30);

        tlfAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(tlfAng);
        tlfAng.setBounds(140, 153, 160, 30);

        mailAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(mailAng);
        mailAng.setBounds(480, 153, 160, 30);

        contAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(contAng);
        contAng.setBounds(140, 200, 160, 30);

        parolaAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        adaugareAngajat.add(parolaAng);
        parolaAng.setBounds(480, 203, 160, 30);

        functieAng.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        functieAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                functieAngActionPerformed(evt);
            }
        });
        adaugareAngajat.add(functieAng);
        functieAng.setBounds(140, 260, 160, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Adauga");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        adaugareAngajat.add(jButton2);
        jButton2.setBounds(180, 360, 116, 45);

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel13.setText("Adaugare Angajati");
        adaugareAngajat.add(jLabel13);
        jLabel13.setBounds(267, 22, 150, 20);

        labelAgentie.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelAgentie.setText("Agentie");
        adaugareAngajat.add(labelAgentie);
        labelAgentie.setBounds(400, 260, 60, 30);

        butonInapoiAdaugare.setBackground(new java.awt.Color(0, 102, 102));
        butonInapoiAdaugare.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        butonInapoiAdaugare.setForeground(new java.awt.Color(255, 255, 255));
        butonInapoiAdaugare.setText("Inapoi");
        butonInapoiAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonInapoiAdaugareActionPerformed(evt);
            }
        });
        adaugareAngajat.add(butonInapoiAdaugare);
        butonInapoiAdaugare.setBounds(510, 360, 120, 40);

        adaugareAngajat.add(agentieAng);
        agentieAng.setBounds(480, 260, 160, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/bgFurnizoriAdmin.jpg"))); // NOI18N
        adaugareAngajat.add(jLabel7);
        jLabel7.setBounds(0, 0, 690, 490);

        getContentPane().add(adaugareAngajat);
        adaugareAngajat.setBounds(0, 0, 700, 480);

        vizualizareFurnizori.setLayout(null);

        titluFurnizori.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        titluFurnizori.setText("FURNIZORI TRANSPORT");
        vizualizareFurnizori.add(titluFurnizori);
        titluFurnizori.setBounds(250, 60, 210, 20);

        tabelFurnizori.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelFurnizori.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Cod Furnizor", "Firma"
                }
        ));
        jScrollPane2.setViewportView(tabelFurnizori);

        vizualizareFurnizori.add(jScrollPane2);
        jScrollPane2.setBounds(120, 150, 450, 110);

        inapoiPagAdmin.setBackground(new java.awt.Color(0, 102, 102));
        inapoiPagAdmin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        inapoiPagAdmin.setForeground(new java.awt.Color(255, 255, 255));
        inapoiPagAdmin.setText("Inapoi");
        inapoiPagAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiPagAdminActionPerformed(evt);
            }
        });
        vizualizareFurnizori.add(inapoiPagAdmin);
        inapoiPagAdmin.setBounds(480, 340, 120, 40);

        butonAdaugaContract.setBackground(new java.awt.Color(0, 102, 102));
        butonAdaugaContract.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonAdaugaContract.setForeground(new java.awt.Color(255, 255, 255));
        butonAdaugaContract.setText("Adaugare Contract");
        butonAdaugaContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonAdaugaContractActionPerformed(evt);
            }
        });
        vizualizareFurnizori.add(butonAdaugaContract);
        butonAdaugaContract.setBounds(70, 340, 170, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/bgFurnizoriAdmin.jpg"))); // NOI18N
        vizualizareFurnizori.add(jLabel3);
        jLabel3.setBounds(0, 0, 690, 490);

        getContentPane().add(vizualizareFurnizori);
        vizualizareFurnizori.setBounds(0, 0, 700, 470);

        cautareAngajat.setLayout(null);

        titluCautareAng.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        titluCautareAng.setText("Cautare Angajat");
        cautareAngajat.add(titluCautareAng);
        titluCautareAng.setBounds(259, 38, 129, 20);

        radioNume.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        radioNume.setText("Nume");
        cautareAngajat.add(radioNume);
        radioNume.setBounds(67, 99, 67, 25);

        radioCod.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        radioCod.setText("Cod");
        cautareAngajat.add(radioCod);
        radioCod.setBounds(67, 145, 74, 25);

        fieldCautare.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cautareAngajat.add(fieldCautare);
        fieldCautare.setBounds(206, 125, 182, 23);

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Inapoi");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        cautareAngajat.add(backButton);
        backButton.setBounds(516, 371, 83, 25);

        tabelAngajat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelAngajat.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Cod", "Nume", "Prenume", "Telefon", "Email", "Functie"
                }
        ));
        jScrollPane4.setViewportView(tabelAngajat);
        if (tabelAngajat.getColumnModel().getColumnCount() > 0) {
            tabelAngajat.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        cautareAngajat.add(jScrollPane4);
        jScrollPane4.setBounds(0, 219, 710, 90);

        butonCautare.setBackground(new java.awt.Color(0, 102, 102));
        butonCautare.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        butonCautare.setForeground(new java.awt.Color(255, 255, 255));
        butonCautare.setText("Cauta");
        butonCautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCautareActionPerformed(evt);
            }
        });
        cautareAngajat.add(butonCautare);
        butonCautare.setBounds(477, 131, 83, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agentieturism/bgFurnizoriAdmin.jpg"))); // NOI18N
        cautareAngajat.add(jLabel8);
        jLabel8.setBounds(0, 0, 710, 480);

        getContentPane().add(cautareAngajat);
        cautareAngajat.setBounds(0, 0, 700, 480);

        meniuAdmin.setForeground(new java.awt.Color(0, 153, 153));
        meniuAdmin.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        vizualizareMeniu.setText("Vizualizare");
        vizualizareMeniu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        vizAngMeniuItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vizAngMeniuItem.setText("Angajati");
        vizAngMeniuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizAngMeniuItemActionPerformed(evt);
            }
        });
        vizualizareMeniu.add(vizAngMeniuItem);

        vizFurnizorMeniuItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vizFurnizorMeniuItem.setText("Furnizori");
        vizFurnizorMeniuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vizFurnizorMeniuItemActionPerformed(evt);
            }
        });
        vizualizareMeniu.add(vizFurnizorMeniuItem);

        meniuAdmin.add(vizualizareMeniu);

        adaugareMeniu.setText("Adaugare");
        adaugareMeniu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        adaugareAngMeniuItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        adaugareAngMeniuItem.setText("Angajati");
        adaugareAngMeniuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugareAngMeniuItemActionPerformed(evt);
            }
        });
        adaugareMeniu.add(adaugareAngMeniuItem);

        adaugareContractItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        adaugareContractItem.setText("Contract");
        adaugareContractItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugareContractItemActionPerformed(evt);
            }
        });
        adaugareMeniu.add(adaugareContractItem);

        meniuAdmin.add(adaugareMeniu);

        cautareMeniu.setText("Cautare");
        cautareMeniu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        cautareAngItem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cautareAngItem.setText("Angajat");
        cautareAngItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautareAngItemActionPerformed(evt);
            }
        });
        cautareMeniu.add(cautareAngItem);

        meniuAdmin.add(cautareMeniu);

        setJMenuBar(meniuAdmin);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void deconectareButonActionPerformed(java.awt.event.ActionEvent evt) {
        JFrame pagPrincipala = new PrimaPagina();
        pagPrincipala.setVisible(true);
        this.dispose();
    }

    private void vizAngMeniuItemActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(vizualizareAngajati);
    }

    private void butonInapoiActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void inapoiPagAdminActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void vizFurnizorMeniuItemActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(vizualizareFurnizori);
    }

    private void adaugareContractItemActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(adaugareContract);
    }

    private void butonAdaugaContractActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(adaugareContract);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        String admin = numeAngajat.getText();
        // String agentie = agentieAng.getSelectedItem().toString();
        String agentie = (String) agentieC.getSelectedItem();
        String furnizor = furnizori.getSelectedItem().toString();
        String data = anul.getSelectedItem() + "-" + luna.getSelectedItem() + "-" + ziua.getSelectedItem();
        int nrContract = 0;

        try {
            Connection conn = getConnection();

            String getCodFurnizor =
                    "SELECT furnizori.cod_furnizor FROM furnizori WHERE firma=?";

            PreparedStatement ps = conn.prepareStatement(getCodFurnizor);
            ps.setString(1, furnizor);
            ResultSet rs = ps.executeQuery();
            int codf = 0;
            while (rs.next()) {
                codf = rs.getInt(1);
            }

            String getCodAgentie = "SELECT cod_agentie FROM agentie WHERE denumire=?";

            PreparedStatement ps3 = conn.prepareStatement(getCodAgentie);
            ps3.setString(1, agentie);
            ResultSet rs2 = ps3.executeQuery();
            int coda = 0;
            while (rs2.next()) {
                coda = rs2.getInt(1);
            }

            PreparedStatement ps1 = conn.prepareStatement("INSERT INTO contract VALUES (1,?,?,?,?)");
            ps1.setInt(1, coda);
            ps1.setInt(2, codf);
            ps1.setNull(3, Types.INTEGER);
            ps1.setString(4, data);
            ps1.executeUpdate();

            String getNrContract = "SELECT MAX(nrcontract) FROM contract";
            PreparedStatement ps2 = conn.prepareStatement(getNrContract);
            ResultSet rs1 = ps2.executeQuery();

            while (rs1.next()) {
                nrContract = rs1.getInt(1);
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate realiza contractul!");

        }
        contractA4.selectAll();
        contractA4.replaceSelection("");
        contractA4.append("\t\n\tCONTRACT DE COLABORARE\n" + "\nNr:\t" + nrContract + "\n\nIntre " + agentie + " cu sediul in "
                + "\nStr. Victoriei, Nr.134 " + "\navand certificat de inmatriculare nr. 19887, " + "\nreprezentata de " +
                admin + " avand functia\n" + "de administrator la agentia \nsi\n" + "SC " + furnizor + " SRL cu sediul in Str X, Nr.120 " +
                "\n\nObiectul contractului " + "\n\nArt. 1 Obiectul prezentului contract consta în " + "\nvânzarea de bilete de transport pe ruta " + "\n– x – y – z cu plecare în zilele de" + "\n joi, vineri si sâmbata.\n" +
                "\n" +
                "Art. 2 Vânzarea si/sau rezervarea biletelor" + "\n de transport se face cu respectarea dispozitiilor" + "\n legale si a celor din prezentul contract." +
                "\n\nIncheiat astazi:\t" + data);
        contractA4.setFont(new Font("Lucida Bright", Font.PLAIN, 12));
        JOptionPane.showMessageDialog(this, "Contract realizat!");


    }

    private void furnizoriButonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(vizualizareFurnizori);
    }

    private void adaugareAngMeniuItemActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(adaugareAngajat);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        String numeAngajatdeAdaugat = numeAng.getText();
        String prenumeAngajat = prenAng.getText();
        String telefon = tlfAng.getText();
        String email = mailAng.getText();
        String cont = contAng.getText();
        String parola = parolaAng.getText();
        String functie = (String) functieAng.getSelectedItem();
        String agentie = (String) agentieAng.getSelectedItem();
        try {
            Connection con = getConnection();
            String getCodFunctie = "SELECT cod_functie FROM functie WHERE Den_functie=?";
            PreparedStatement ps = con.prepareStatement(getCodFunctie);
            ps.setString(1, functie);
            ResultSet rs = ps.executeQuery();
            int codf = 0;
            while (rs.next()) {
                codf = rs.getInt(1);
            }

            String getCodAgentie = "SELECT cod_agentie FROM agentie WHERE denumire=?";
            PreparedStatement ps2 = con.prepareStatement(getCodAgentie);
            ps2.setString(1, agentie);
            ResultSet rs2 = ps2.executeQuery();
            int coda = 0;
            while (rs2.next()) {
                coda = rs2.getInt(1);
            }

            PreparedStatement ps1 = con.prepareStatement("INSERT INTO angajat VALUES (null,?,?,?,?,?,?,?,?)");

            ps1.setString(1, numeAngajatdeAdaugat);
            ps1.setString(2, prenumeAngajat);
            ps1.setString(3, telefon);
            ps1.setString(4, email);
            ps1.setString(5, cont);
            ps1.setString(6, parola);
            ps1.setInt(7, codf);
            ps1.setInt(8, coda);
            if (!numeAngajatdeAdaugat.matches("[A-Za-z]*")) {
                JOptionPane.showMessageDialog(this, "Introduceti numai litere in campul nume!");
            } else if (!prenumeAngajat.matches("[A-Za-z]*")) {
                JOptionPane.showMessageDialog(this, "Introduceti numai litere in campul prenume!");
            } else if (!telefon.matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Introduceti numai cifre in campul telefon!");
                // } else if(!email.matches("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\\\.[A-Z]{2,6}$")){
                //     JOptionPane.showMessageDialog(this,"Email invalid");
            } else {
                ps1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Angajatul a fost adaugat!");
                numeAng.setText("");
                prenAng.setText("");
                tlfAng.setText("");
                mailAng.setText("");
                contAng.setText("");
                parolaAng.setText("");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate insera angajatul");

        }
    }

    private void cautareAngItemActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(cautareAngajat);
    }

    private void butonCautareActionPerformed(java.awt.event.ActionEvent evt) {
        String text = fieldCautare.getText();
        DefaultTableModel model = (DefaultTableModel) tabelAngajat.getModel();

        try {
            Connection con = getConnection();
            String functie = "SELECT den_functie FROM functie, angajat WHERE functie.cod_functie = angajat.cod_functie";
            PreparedStatement pstm = con.prepareStatement(functie);
            ResultSet rs1 = pstm.executeQuery();
            if (radioNume.isSelected() == true) {
                String query = "SELECT * FROM angajat WHERE nume=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, text);
                ResultSet rs = ps.executeQuery();
                while (rs.next() && rs1.next()) {
                    model.addRow(new Object[]{"" + rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),
                            rs1.getString(1)});
                }
                fieldCautare.setText("");
                radioNume.setSelected(false);
            } else if (radioCod.isSelected() == true) {
                String query = "SELECT * FROM angajat WHERE cod_angajat=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, text);
                ResultSet rs = ps.executeQuery();
                while (rs.next() && rs1.next()) {
                    model.addRow(new Object[]{"" + rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),
                            rs1.getString(1)});
                }
                fieldCautare.setText("");
                radioCod.setSelected(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Eroare cautare angajat");
        }
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void contracteButonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(adaugareContract);
    }

    private void emailContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void contContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void parolaContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void prenumeContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void telefonContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void numeContActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void contulMeuButonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(contulMeu);
    }

    private void agentiiButonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(angajatiVizSiAdaug);
    }

    private void butonInapoiContActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void butonSalveazaActionPerformed(java.awt.event.ActionEvent evt) {
        String nume = numeCont.getText();
        String prenume = prenumeCont.getText();
        String telefon = telefonCont.getText();
        String email = emailCont.getText();
        String cont = contCont.getText();
        String parola = parolaCont.getText();
        Connection conn = null;
        PreparedStatement ps = null;
        try {
            conn = getConnection();
            String updateCont = "UPDATE angajat SET nume=?, prenume=?, telefon=?, email=?, cont=?, parola=? WHERE cont=?";
            ps = conn.prepareStatement(updateCont);
            ps.setString(1, nume);
            ps.setString(2, prenume);
            ps.setString(3, telefon);
            ps.setString(4, email);
            ps.setString(5, cont);
            ps.setString(6, parola);
            ps.setString(7, campUser.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Actualizarea a reusit!");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Actualizare esuata!");
        } finally {
            codFinally(null, ps, conn);
        }
    }

    private void butonInapoiAngActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);

    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

        String denAgentiedeInserat = denAg1.getText();
        String telefon = tlfAg1.getText();
        String adresa = addAg1.getText();
        ;
        Connection con = null;
        PreparedStatement ps1 = null;
        try {
            con = getConnection();

            ps1 = con.prepareStatement("INSERT INTO agentie VALUES (null,?,?,?)");

            ps1.setString(1, denAgentiedeInserat);
            ps1.setString(2, adresa);
            ps1.setString(3, telefon);

            ps1.executeUpdate();
            JOptionPane.showMessageDialog(this, "Agentia a fost adaugata!");
            denAg1.setText("");
            tlfAg1.setText("");
            addAg1.setText("");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate insera agentia");

        } finally {
            codFinally(null, ps1, con);
        }
    }

    private void lunaActionPerformed(java.awt.event.ActionEvent evt) {

        if (luna.getSelectedItem().equals("2") && anBisect(Integer.parseInt(anul.getSelectedItem().toString()))) {
            ziua.removeAllItems();
            for (int i = 1; i <= 29; i++) {
                ziua.addItem(Integer.toString(i));
            }
        } else if (luna.getSelectedItem().equals("2") && anBisect(Integer.parseInt(anul.getSelectedItem().toString())) == false) {
            ziua.removeAllItems();
            for (int i = 1; i <= 28; i++) {
                ziua.addItem(Integer.toString(i));
            }
        } else if (luna.getSelectedItem().equals("1") || luna.getSelectedItem().equals("3") || luna.getSelectedItem().equals("5") || luna.getSelectedItem().equals("7") || luna.getSelectedItem().equals("8") || luna.getSelectedItem().equals("10") || luna.getSelectedItem().equals("12")) {
            ziua.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                ziua.addItem(Integer.toString(i));
            }
        } else {
            ziua.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                ziua.addItem(Integer.toString(i));
            }
        }
    }

    private void anulActionPerformed(java.awt.event.ActionEvent evt) {


    }

    private void salvareContractActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser save = new JFileChooser();
        int option = save.showSaveDialog(this);
        File file = new File(save.getSelectedFile().getPath());

        try {
            String source = contractA4.getText();
            char buffer[] = new char[source.length()];
            source.getChars(0, source.length(), buffer, 0);

            try (FileWriter f1 = new FileWriter(file + ".txt")) {
                for (int i = 0; i < buffer.length; i++) {
                    f1.write(buffer[i]);
                }
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate salva!");
        }


    }

    private void butonInapoiAdaugareActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void butonInapoiContractActionPerformed(java.awt.event.ActionEvent evt) {
        contractA4.selectAll();
        contractA4.replaceSelection("");
        setPanelVisible(pagPrincAdmin);
    }

    private void rapoarteButonActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(raportPanel);
    }

    private void comboAnulActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void comboLunaActionPerformed(java.awt.event.ActionEvent evt) {
        if (comboLuna.getSelectedItem().equals("2") && anBisect(Integer.parseInt(comboAnul.getSelectedItem().toString()))) {
            comboZiua.removeAllItems();
            for (int i = 1; i <= 29; i++) {
                comboZiua.addItem(Integer.toString(i));
            }
        } else if (comboLuna.getSelectedItem().equals("2") && anBisect(Integer.parseInt(comboAnul.getSelectedItem().toString())) == false) {
            comboZiua.removeAllItems();
            for (int i = 1; i <= 28; i++) {
                comboZiua.addItem(Integer.toString(i));
            }
        } else if (comboLuna.getSelectedItem().equals("1") || comboLuna.getSelectedItem().equals("3") || comboLuna.getSelectedItem().equals("5") || comboLuna.getSelectedItem().equals("7") || comboLuna.getSelectedItem().equals("8") || comboLuna.getSelectedItem().equals("10") || comboLuna.getSelectedItem().equals("12")) {
            comboZiua.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                comboZiua.addItem(Integer.toString(i));
            }
        } else {
            comboZiua.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                comboZiua.addItem(Integer.toString(i));
            }
        }
    }

    private void comboAnul1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void comboLuna1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (comboLuna1.getSelectedItem().equals("2") && anBisect(Integer.parseInt(comboAnul1.getSelectedItem().toString()))) {
            comboZiua1.removeAllItems();
            for (int i = 1; i <= 29; i++) {
                comboZiua1.addItem(Integer.toString(i));
            }
        } else if (comboLuna1.getSelectedItem().equals("2") && anBisect(Integer.parseInt(comboAnul1.getSelectedItem().toString())) == false) {
            comboZiua1.removeAllItems();
            for (int i = 1; i <= 28; i++) {
                comboZiua1.addItem(Integer.toString(i));
            }
        } else if (comboLuna1.getSelectedItem().equals("1") || comboLuna1.getSelectedItem().equals("3") || comboLuna1.getSelectedItem().equals("5") || comboLuna1.getSelectedItem().equals("7") || comboLuna1.getSelectedItem().equals("8") || comboLuna1.getSelectedItem().equals("10") || comboLuna1.getSelectedItem().equals("12")) {
            comboZiua1.removeAllItems();
            for (int i = 1; i <= 31; i++) {
                comboZiua1.addItem(Integer.toString(i));
            }
        } else {
            comboZiua1.removeAllItems();
            for (int i = 1; i <= 30; i++) {
                comboZiua1.addItem(Integer.toString(i));
            }
        }
    }

    private void butonAfisareActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) tabelRaport.getModel();
        try {
            Connection con = getConnection();
            String sql = "select oras_sosire,data_plecare, data_sosire, count(rezervare_sejur.cod_sejur) from sejur, rezervare_sejur where sejur.cod_sejur = rezervare_sejur.cod_sejur and data_plecare between ? and ? group by oras_sosire";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setString(1, comboAnul.getSelectedItem().toString() + "-" + comboLuna.getSelectedItem().toString() + "-" + comboZiua.getSelectedItem().toString());
            pstm.setString(2, comboAnul1.getSelectedItem().toString() + "-" + comboLuna1.getSelectedItem().toString() + "-" + comboZiua1.getSelectedItem().toString());
            ResultSet rs = pstm.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{"" + rs.getString(1), rs.getString(2), rs.getString(3), rs.getInt(4)});

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Nu se pot afisa datele!");
        }
    }

    private void butonBDFActionPerformed(java.awt.event.ActionEvent evt) {

        DefaultPieDataset myPiedataset = new DefaultPieDataset();
        ArrayList<String> destinatii = new ArrayList<>();
        ArrayList<Integer> numar_rezervari = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tabelRaport.getModel();
        for (int i = 0; i < tabelRaport.getRowCount(); i++) {
            destinatii.add(model.getValueAt(i, 0).toString());
            numar_rezervari.add((Integer) model.getValueAt(i, 3));
        }
        for (int i = 0; i < destinatii.size(); i++) {
            myPiedataset.setValue(destinatii.get(i), numar_rezervari.get(i));
        }
        JFreeChart chart = ChartFactory.createPieChart("Destinatii cautate", myPiedataset, true, true, false);
        PdfWriter writer = null;
        Document document = new Document();

        try {

            writer = PdfWriter.getInstance(document, new FileOutputStream(
                    "destinatii"));
            document.open();
            PdfContentByte contentByte = writer.getDirectContent();
            PdfTemplate template = contentByte.createTemplate(300, 300);
            Graphics2D graphics2d = template.createGraphics(300, 300,
                    new DefaultFontMapper());
            Rectangle2D rectangle2d = new Rectangle2D.Double(0, 0, 300,
                    300);

            chart.draw(graphics2d, rectangle2d);

            graphics2d.dispose();
            contentByte.addTemplate(template, 250, 250);

            Paragraph paragraph = new Paragraph();
            paragraph.add("RAPORT\n");
            paragraph.add("Destinatii cautate\n\n");
            document.add(paragraph);

            PdfPTable pdfTable = new PdfPTable(tabelRaport.getColumnCount());
            for (int i = 0; i < tabelRaport.getColumnCount(); i++) {
                pdfTable.addCell(tabelRaport.getColumnName(i));
            }
            for (int rows = 0; rows < tabelRaport.getRowCount(); rows++) {
                for (int cols = 0; cols < tabelRaport.getColumnCount(); cols++) {
                    pdfTable.addCell(tabelRaport.getModel().getValueAt(rows, cols).toString());

                }
            }
            document.add(pdfTable);
            document.close();
            JOptionPane.showMessageDialog(this, "PDF generat!");
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, "Nu se poate genera PDF-ul!");
        }
        document.close();

    }

    private void butonDiagramaActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultPieDataset myPiedataset = new DefaultPieDataset();
        ArrayList<String> destinatii = new ArrayList<>();
        ArrayList<Integer> numar_rezervari = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tabelRaport.getModel();
        for (int i = 0; i < tabelRaport.getRowCount(); i++) {
            destinatii.add(model.getValueAt(i, 0).toString());
            numar_rezervari.add((Integer) model.getValueAt(i, 3));
        }
        for (int i = 0; i < destinatii.size(); i++) {
            myPiedataset.setValue(destinatii.get(i), numar_rezervari.get(i));
        }
        JFreeChart chart = ChartFactory.createPieChart("Destinatii", myPiedataset, true, true, false);
        PiePlot p = (PiePlot) chart.getPlot();
        ChartFrame frame = new ChartFrame("Raport", chart);
        frame.setVisible(true);
        frame.setSize(450, 500);

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        setPanelVisible(pagPrincAdmin);
    }

    private void denAg1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void functieAngActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tabelAgentiiMouseClicked(java.awt.event.MouseEvent evt) {


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PaginaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem adaugareAngMeniuItem;
    private javax.swing.JPanel adaugareAngajat;
    private javax.swing.JPanel adaugareContract;
    private javax.swing.JMenuItem adaugareContractItem;
    private javax.swing.JMenu adaugareMeniu;
    private javax.swing.JTextField addAg1;
    private javax.swing.JComboBox<String> agentieAng;
    private javax.swing.JComboBox<String> agentieC;
    private javax.swing.JButton agentiiButon;
    private javax.swing.JPanel angajatiVizSiAdaug;
    private javax.swing.JComboBox<String> anul;
    private javax.swing.JButton backButton;
    private javax.swing.JButton butonAdaugaContract;
    private javax.swing.JButton butonAfisare;
    private javax.swing.JButton butonBDF;
    private javax.swing.JButton butonCautare;
    private javax.swing.JButton butonDiagrama;
    private javax.swing.JButton butonInapoi;
    private javax.swing.JButton butonInapoiAdaugare;
    private javax.swing.JButton butonInapoiAng;
    private javax.swing.JButton butonInapoiCont;
    private javax.swing.JButton butonInapoiContract;
    private javax.swing.JButton butonSalveaza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JMenuItem cautareAngItem;
    private javax.swing.JPanel cautareAngajat;
    private javax.swing.JMenu cautareMeniu;
    private javax.swing.JComboBox<String> comboAnul;
    private javax.swing.JComboBox<String> comboAnul1;
    private javax.swing.JComboBox<String> comboLuna;
    private javax.swing.JComboBox<String> comboLuna1;
    private javax.swing.JComboBox<String> comboZiua;
    private javax.swing.JComboBox<String> comboZiua1;
    private javax.swing.JTextField contAng;
    private javax.swing.JTextField contCont;
    private javax.swing.JTextArea contractA4;
    private javax.swing.JButton contracteButon;
    private javax.swing.JPanel contulMeu;
    private javax.swing.JButton contulMeuButon;
    private javax.swing.JButton deconectareButon;
    private javax.swing.JTextField denAg1;
    private javax.swing.JTextField emailCont;
    private javax.swing.JTextField fieldCautare;
    private javax.swing.JComboBox<String> functieAng;
    private javax.swing.JComboBox<String> furnizori;
    private javax.swing.JButton furnizoriButon;
    private javax.swing.JLabel imgProfilAng;
    private javax.swing.JButton inapoiPagAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelAdresa1;
    private javax.swing.JLabel labelAgentie;
    private javax.swing.JLabel labelCont;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDen1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFunctie;
    private javax.swing.JLabel labelFurnizor;
    private javax.swing.JLabel labelNume;
    private javax.swing.JLabel labelNumeAngajat;
    private javax.swing.JLabel labelParola;
    private javax.swing.JLabel labelPrenume;
    private javax.swing.JLabel labelTelefon;
    private javax.swing.JLabel labelTelefon1;
    private javax.swing.JLabel logoAdmin;
    private javax.swing.JComboBox<String> luna;
    private javax.swing.JTextField mailAng;
    private javax.swing.JMenuBar meniuAdmin;
    private javax.swing.JTextField numeAng;
    private javax.swing.JTextField numeAngajat;
    private javax.swing.JTextField numeCont;
    private javax.swing.JPanel pagPrincAdmin;
    private javax.swing.JTextField parolaAng;
    private javax.swing.JTextField parolaCont;
    private javax.swing.JTextField prenAng;
    private javax.swing.JTextField prenumeCont;
    private javax.swing.JRadioButton radioCod;
    private javax.swing.JRadioButton radioNume;
    private javax.swing.JButton rapoarteButon;
    private javax.swing.JPanel raportPanel;
    private javax.swing.JButton salvareContract;
    private javax.swing.JTable tabelAgentii;
    private javax.swing.JTable tabelAngajat;
    private javax.swing.JTable tabelAngajati;
    private javax.swing.JTable tabelFurnizori;
    private javax.swing.JTable tabelRaport;
    private javax.swing.JTextField telefonCont;
    private javax.swing.JLabel titluAng;
    private javax.swing.JLabel titluAngajati;
    private javax.swing.JLabel titluCautareAng;
    private javax.swing.JLabel titluContulMeu;
    private javax.swing.JLabel titluFurnizori;
    private javax.swing.JTextField tlfAg1;
    private javax.swing.JTextField tlfAng;
    private javax.swing.JMenuItem vizAngMeniuItem;
    private javax.swing.JMenuItem vizFurnizorMeniuItem;
    private javax.swing.JPanel vizualizareAngajati;
    private javax.swing.JPanel vizualizareFurnizori;
    private javax.swing.JMenu vizualizareMeniu;
    private javax.swing.JComboBox<String> ziua;
    // End of variables declaration
}
